application: openscrum-dev
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /client
  static_dir: client

- url: /client_mm
  static_dir: client_mm

- url: /cron/.*
  script: openscrum.app
  login: admin 

- url: /.*
  script: openscrum.app

builtins:
- appstats: on
